export { default as NavBar } from './common/NavBar'
export { default as About } from './sections/About'
export { default as Contact } from './sections/Contact'
export { default as Hero } from './sections/Hero'
export { default as Projects } from './sections/Projects'